const Embeds = require('./embeds.js');

exports.voiceObject = {
    "!pancake": {file: 'pancake.mp3', categories: ["Meme"], categoriesFortnite: ["afterlose"]},
    "!whoops": {file: 'whoops.mp3', categories: ["Meme"], categoriesFortnite: ["afterlose", "afterwin"]},
    "!magnumdong": {file: 'magnumdong.mp3', categories: ["Meme"], categoriesFortnite: ["afterlose"]},
    "!gotem": {file: 'gotem.mp3', categories: ["Meme"], categoriesFortnite: ["afterwin"]},
    "!niet": {file: 'niet.mp3', categories: ["Reaction 😯"], categoriesFortnite: []},
    "!glitter": {file: 'glitter.mp3', categories: ["Meme"], categoriesFortnite: ["afterwin"]},
    "!darkness": {file: 'darkness.mp3', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!regret": {file: 'sad.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!shots": {file: 'shots.mp3', categories: ["Reaction 😯"], categoriesFortnite: ["afterwin"]},
    "!cant": {file: 'cant.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!die": {file: 'die.mp3', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!freestyler": {file: 'freestyler.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterwin", "beforematch"]},
    "!wtf": {file: 'wtf.mp3', categories: ["Reaction 😯"], categoriesFortnite: ["afterwin", "afterlose"]},
    "!lidl": {file: 'lidl.mp3', categories: ["Meme"], categoriesFortnite: ["afterwin"]},
    "!badum": {file: 'badum.mp3', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!nexttime": {file: 'nexttime.mp3', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!no": {file: 'no.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!never": {file: 'never.wav', categories: ["Motivation 💪"], categoriesFortnite: ["afterlose"]},
    "!lying": {file: 'lying.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!wahahou": {file: 'wahahou.wav', categories: ["Meme"], categoriesFortnite: ["afterlose", "afterwin"]},
    "!chocola": {file: 'chocola.wav', categories: ["Meme"], categoriesFortnite: []},
    "!profanity": {file: 'profanity.wav', categories: ["Funny 😂"], categoriesFortnite: []},
    "!tongue": {file: 'tongue.wav', categories: ["Meme"], categoriesFortnite: ["beforematch"]},
    "!alright": {file: 'alright.wav', categories: ["Funny 😂"], categoriesFortnite: ["afterlose"]},
    "!goodbye": {file: 'goodbye.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!komtgoed": {file: 'komtgoed.wav', categories: ["Motivation 💪"], categoriesFortnite: ["afterlose"]},
    "!poep": {file: 'poep.wav', categories: ["Meme"], categoriesFortnite: ["afterlose"]},
    "!bingo": {file: 'bingo.wav', categories: ["Funny 😂"], categoriesFortnite: ["afterlose"]},
    "!myself": {file: 'myself.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose", "afterwin"]},
    "!houston": {file: 'houston.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!try": {file: 'try.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!tears": {file: 'tears.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!endworld": {file: 'endworld.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!missyou": {file: 'missyou.wav', categories: ["Sad 😭"], categoriesFortnite: []},
    "!together": {file: 'together.wav', categories: ["Motivation 💪"], categoriesFortnite: ["beforematch"]},
    "!steeds": {file: 'steeds.wav', categories: ["Funny 😂"], categoriesFortnite: ["afterlose"]},
    "!hello": {file: 'hello.wav', categories: ["Meme"], categoriesFortnite: []},
    "!tochniet": {file: 'tochniet.wav', categories: ["Funny 😂"], categoriesFortnite: ["afterlose"]},
    "!skill": {file: 'skill.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterwin"]},
    "!dumb": {file: 'dumb.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!biem": {file: 'biem.wav', categories: ["Meme"], categoriesFortnite: ["afterwin"]},
    "!fine": {file: 'fine.mp3', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!duuun": {file: 'duuun.mp3', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterwin"]},
    "!happened": {file: 'happened.mp3', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose", "afterwin"]},
    "!killmyself": {file: 'killmyself.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!rustaagh": {file: 'rustaagh.mp3', categories: ["Reaction 😯"], categoriesFortnite: ["afterwin"]},
    "!dunked": {file: 'dunked.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose", "afterwin"]},
    "!infinity": {file: 'infinity.mp3', categories: ["Motivation 💪"], categoriesFortnite: ["beforematch"]},
    "!feelsbad": {file: 'sad.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!herewego": {file: 'herewego.mp3', categories: ["Gamen :video_game:"], categoriesFortnite: ["beforematch"]},
    "!mission": {file: 'mission.mp3', categories: ["Gamen :video_game:"], categoriesFortnite: []},
    "!rip": {file: 'rip.mp3', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!trombone": {file: 'trombone.mp3', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!start": {file: 'start.mp3', categories: ["Gamen :video_game:"], categoriesFortnite: ["beforematch"]},
    "!noone": {file: 'noone.mp3', categories: ["Funny 😂"], categoriesFortnite: ["afterwin", "afterlose"]},
    "!damnson": {file: 'damnson.mp3', categories: ["Funny 😂"], categoriesFortnite: ["afterlose", "afterwin"]},
    "!tadaah": {file: 'tadaah.mp3', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose", "afterwin"]},
    "!pressure": {file: 'pressure.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["beforematch"]},
    "!kapitein": {file: 'kapitein.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose"]},
    "!nigga": {file: 'nigga.mp3', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!like": {file: 'like.mp3', categories: ["Meme"], categoriesFortnite: ["afterlose","afterwin"]},
    "!smooth": {file: 'smooth.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose","afterwin"]},
    "!behappy": {file: 'behappy.wav', categories: ["Motivation 💪"], categoriesFortnite: ["afterlose","afterwin","beforematch"]},
    "!river": {file: 'river.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!mylife": {file: 'mylife.wav', categories: ["Motivation 💪"], categoriesFortnite: ["beforematch"]},
    "!gratis": {file: 'gratis.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterwin"]},
    "!how": {file: 'how.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!letsdoit": {file: 'letsdoit.wav', categories: ["Motivation 💪"], categoriesFortnite: ["beforematch"]},
    "!uhm": {file: 'uhm.wav', categories: ["Meme"], categoriesFortnite: ["afterlose"]},
    "!hehe": {file: 'hehe.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterwin"]},
    "!rutte": {file: 'rutte.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!gohome": {file: 'gohome.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!whatyoudoing": {file: 'whatyoudoing.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose","afterwin"]},
    "!dontthinkso": {file: 'dontthinkso.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose","beforematch"]},
    "!ruined": {file: 'ruined.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose"]},
    "!vibeit": {file: 'vibeit.wav', categories: ["Motivation 💪"], categoriesFortnite: ["beforematch"]},
    "!omgwow": {file: 'omgwow.mp3', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose","afterwin"]},
    "!sperdnigga": {file: 'sperdnigga.mp3', categories: ["Meme"], categoriesFortnite: ["afterlose"]},
    "!mbaku": {file: 'mbaku.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!meneerdeboer": {file: 'meneerdeboer.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose"]},
    "!hellothere": {file: 'hellothere.wav', categories: ["Meme"], categoriesFortnite: ["afterwin"]},
    "!running": {file: 'running.mp3', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose"]},
    "!cyka": {file: 'cyka.wav', categories: ["Funny 😂"], categoriesFortnite: ["afterlose","afterwin"]},
    "!verkeerd": {file: 'verkeerd.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!klaas": {file: 'klaas.wav', categories: ["Funny 😂"], categoriesFortnite: ["afterlose"]},
    "!sjoerd": {file: 'sjoerd.wav', categories: ["Funny 😂"], categoriesFortnite: ["afterlose"]},
    "!wout": {file: 'wout.wav', categories: ["Funny 😂"], categoriesFortnite: ["afterlose"]},
    "!bush": {file: 'bush.wav', categories: ["Gamen :video_game:"], categoriesFortnite: []},
    "!familiar": {file: 'familiar.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!freedom": {file: 'freedom.wav', categories: ["Motivation 💪"], categoriesFortnite: ["beforematch"]},
    "!perfect": {file: 'perfect.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!kind": {file: 'kind.wav', categories: ["Motivation 💪"], categoriesFortnite: []},
    "!communicate": {file: 'communicate.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose"]},
    "!mad": {file: 'mad.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!seatbelts": {file: 'seatbelts.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["beforematch"]},
    "!roads": {file: 'roads.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["beforematch"]},
    "!shirley": {file: 'shirley.wav', categories: ["Meme"], categoriesFortnite: []},
    "!friendship": {file: 'friendship.wav', categories: ["Motivation 💪"], categoriesFortnite: ["afterwin"]},
    "!prepare": {file: 'prepare.wav', categories: ["Gamen :video_game:"], categoriesFortnite: []},
    "!goodbye2": {file: 'goodbye2.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!goodbye3": {file: 'goodbye3.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!goodbye4": {file: 'goodbye4.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!goodbye5": {file: 'goodbye5.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!anotherone": {file: 'anotherone.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose", "afterwin"]},
    "!liefde": {file: 'liefde.wav', categories: ["Sad 😭"], categoriesFortnite: ["afterlose"]},
    "!mahboi": {file: 'mahboi.mp3', categories: ["Motivation 💪"], categoriesFortnite: ["afterlose", "afterwin"]},
    "!leftchat": {file: 'leftchat.mp3', categories: ["Reaction 😯"], categoriesFortnite: []},
    "!run": {file: 'run.mp3', categories: ["Gamen :video_game:"], categoriesFortnite: []},
    "!hallo": {file: 'hallo.mp3', categories: ["Motivation 💪"], categoriesFortnite: ["beforematch"]},
    "!disappointed": {file: 'disappointment.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!damage": {file: 'damage.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose", "afterwin"]},
    "!jeroen": {file: 'jeroen.wav', categories: ["Meme",], categoriesFortnite: []},
    "!jeff": {file: 'jeff.mp3', categories: ["Meme"], categoriesFortnite: []},
    "!flip": {file: 'flip.mp3', categories: ["Funny 😂"], categoriesFortnite: ["beforematch"]},
    "!klokhuis": {file: 'klokhuis.mp3', categories: ["Funny 😂"], categoriesFortnite: ["beforematch"]},
    "!keukenrol": {file: 'keukenrol.wav', categories: ["Meme"], categoriesFortnite: ["afterlose"]},
    "!nietleuk": {file: 'nietleuk.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!nietnormaal": {file: 'nietnormaal.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!blikje": {file: 'blikje.wav', categories: ["Meme"], categoriesFortnite: ["afterlose", "beforematch"]},
    "!black": {file: 'black.wav', categories: ["Funny 😂"], categoriesFortnite: []},
    "!magic": {file: 'magic.wav', categories: ["Motivation 💪"], categoriesFortnite: ["beforematch"]},
    "!watdoejij": {file: 'watdoejij.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!survivor": {file: 'survivor.wav', categories: ["Motivation 💪"], categoriesFortnite: ["afterwin", "beforematch"]},
    "!lebronjames": {file: 'lebronjames.mp3', categories: ["Meme"], categoriesFortnite: ["afterwin", "beforematch"]},
    "!laugh": {file: 'laugh.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!heyboys": {file: 'heyboys.mp3', categories: ["Reaction 😯"], categoriesFortnite: ["beforematch"]},
    "!verloren": {file: 'verloren.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose"]},
    "!slapen": {file: 'slapen.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose"]},
    "!pain": {file: 'pain.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose"]},
    "!wegotem": {file: 'wegotem.wav', categories: ["Meme"], categoriesFortnite: ["afterwin"]},
    "!sneaky": {file: 'sneaky.wav', categories: ["Meme"], categoriesFortnite: ["beforematch"]},
    "!tasty": {file: 'tasty.wav', categories: ["Funny 😂"], categoriesFortnite: ["afterwin"]},
    "!ahhhhh": {file: 'ahhhhh.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!wednesday": {file: 'wednesday.wav', categories: ["Meme"], categoriesFortnite: ["beforematch"]},
    "!12oclock": {file: '12oclock.wav', categories: ["Meme"], categoriesFortnite: ["beforematch"]},
    "!surrender": {file: 'surrender.wav', categories: ["Motivation 💪"], categoriesFortnite: ["afterlose", "beforematch"]},
    "!whoowee": {file: 'whoowee.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterwin", "beforematch"]},
    "!tequila": {file: 'tequila.wav', categories: ["Meme"], categoriesFortnite: ["beforematch"]},
    "!okbye": {file: 'okbye.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!donald": {file: 'donald.wav', categories: ["Meme"], categoriesFortnite: []},
    "!holdup": {file: 'holdup.wav', categories: ["Meme"], categoriesFortnite: ["afterwin"]},
    "!bye": {file: 'bye.wav', categories: ["Meme"], categoriesFortnite: ["afterlose"]},
    "!highground": {file: 'highground.wav', categories: ["Meme"], categoriesFortnite: []},
    "!yaboi": {file: 'yaboi.wav', categories: ["Meme"], categoriesFortnite: []},
    "!blauwehuis": {file: 'blauwehuis.wav', categories: ["Gamen :video_game:"], categoriesFortnite: []},
    "!ohhoi": {file: 'ohhoi.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterwin"]},
    "!eric": {file: 'eric.wav', categories: ["Funny 😂"], categoriesFortnite: ["afterlose"]},
    "!secrets": {file: 'secrets.wav', categories: ["Reaction 😯"], categoriesFortnite: []},
    "!midget": {file: 'midget.wav', categories: ["Reaction 😯"], categoriesFortnite: []},
    "!sax": {file: 'sax.wav', categories: ["Meme"], categoriesFortnite: ["afterwin"]},
    "!nitraatje": {file: 'nitraatje.wav', categories: ["Meme"], categoriesFortnite: ["beforematch"]},
    "!slecht": {file: 'slecht.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!nogeen": {file: 'nogeen.wav', categories: ["Gamen :video_game:"], categoriesFortnite: ["afterlose"]},
    "!gay": {file: 'gay.wav', categories: ["Meme"], categoriesFortnite: ["afterlose", "afterwin"]},
    "!retarded": {file: 'retarded.wav', categories: ["Reaction 😯"], categoriesFortnite: ["afterlose"]},
    "!helpme": {file: 'helpme.wav', categories: ["Reaction 😯"], categoriesFortnite: ["beforematch"]},

};

exports.responseObject = {
    "ayy": "Ayy, lmao!",
    "wat": "Say what?",
    "lol": "+lol=",
    "+lol=": "hihi",
    "!test": "Yes I am online :)",
    "ping": "pong",
    "pong": "ping",
    "pief": "paf",
    "paf": "pief",
    "sup": "The Sky",
    "oh shit waddup": "The Sky",
    "!stats steam holmes": "!stats steam 76561198152188680",
    "!niceshot": "https://gfycat.com/QuarrelsomeUnawareIslandwhistler",
    "nice shot": "https://gfycat.com/QuarrelsomeUnawareIslandwhistler",
    "🏓": "🏓",
    "regret": "Did you say regret!?",
    "dab": "Did you say dab!?",
    "!hackerman": "https://giphy.com/gifs/fury-kung-hackerman-QbumCX9HFFDQA",
    "hihi": "met",
    "!fortnite": "`!afterlose`\n`!afterwin`\n`!beforematch`",
    "!categories": "`!recentlyadded`\n`!reaction`\n`!gamen`\n`!motivation`\n`!sad`\n`!meme`\n`!funny`\n"
};

exports.imageObject = {
    "regret": './regret.png',
    "!regret": './regret.png',
    "dab": './dab.png',
    "nigga": './nigga.png',
    "really nigga": './nigga.png',
    "!nigga": './nigga.png',
    "meirl": './meirl2.png',
    "meirll": './meirl.png',
    "meirlll": './meirlmerge.jpg',
    "hihi met": './sisi2.jpg',
    "hihi": './sisi.png',
    "keukenrol": './keukenrol.jpg',
    "hap": './hap.png'
}

exports.emojiObject = {
    "gotem": "457243138617245717",
    "yeah": "458285126883999745",
    "no u": "458285126883999745",
    "p!pokemon": "493406516280295435",
    "p!info": "493406516280295435",
    "pokemon": "493406516280295435",
    "༼ つ ◕_ ◕ ༽つ GIVE POKEMON": "493406516280295435",
    "perfectly balanced": "493406616461246475",
    "c_":"457225335801643009",
    "ofneetochniet":"457225416214708226",
    "rl":"457225507117858835",
    "1_":"457225507201875968",
    "facepalm":"457225507214458881",
    "rlball":"457225507742941195",
    "gay":"457226877677993994",
    "noanime":"457226890759897102",
    "hurrthink":"457226984662106125",
    "hmMMM":"457227020594839572",
    "feels":"457237396807745548",
    "chewie":"457237785925910529",
    "suicide":"457238599872544789",
    "eggplanting":"457238600275197952",
    "mood":"457238932489240580",
    "racist":"457238933168717837",
    "gayemoji":"457239160475090956",
    "sup":"457241397267922944",
    "ironic":"457241862571294732",
    "ainsley":"457243138617245717",
    "feline":"457854182599163904",
    "sisi":"457873016702107648",
    "aw_yeah":"458285126883999745",
    "thanos":"459295496255569970",
    "heyguys":"492707094168862721",
    "pikachu":"493406516280295435"
}

exports.embeds = {
    "!commands": Embeds.commands,
    "!help": Embeds.commands,
    "!pp": Embeds.commands,
    "!all": Embeds.allCommands,
    "!chat": Embeds.chatCommands,
    "!voicechat": Embeds.voiceCommands
}