const Embeds = require('./embeds.js');

exports.voiceObject = {
    "!pancake": {file: 'pancake.mp3', categories: [], categoriesFortnite: ["afterLose"]},
    "!whoops": {file: 'whoops.mp3', categories: [], categoriesFortnite: ["afterLose", "afterWin"]},
    "!magnumdong": {file: 'magnumdong.mp3', categories: [], categoriesFortnite: ["afterLose"]},
    "!gotem": {file: 'gotem.mp3', categories: [], categoriesFortnite: ["afterWin"]},
    "!niet": {file: 'glitter.mp3', categories: [], categoriesFortnite: []},
    "!glitter": {file: 'pancake.mp3', categories: [], categoriesFortnite: ["afterWin"]},
    "!darkness": {file: 'darkness.mp3', categories: [], categoriesFortnite: ["afterLose"]},
    "!regret": {file: 'sad.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!shots": {file: 'shots.mp3', categories: [], categoriesFortnite: ["afterWin"]},
    "!cant": {file: 'cant.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!die": {file: 'die.mp3', categories: [], categoriesFortnite: ["afterLose"]},
    "!freestyler": {file: 'freestyler.wav', categories: [], categoriesFortnite: ["afterWin", "beforeMatch"]},
    "!wtf": {file: 'wtf.mp3', categories: [], categoriesFortnite: ["afterWin", "afterLose"]},
    "!lidl": {file: 'lidl.mp3', categories: [], categoriesFortnite: ["afterWin"]},
    "!badum": {file: 'badum.mp3', categories: [], categoriesFortnite: ["afterLose"]},
    "!nexttime": {file: 'nexttime.mp3', categories: [], categoriesFortnite: ["afterLose"]},
    "!no": {file: 'no.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!never": {file: 'never.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!lying": {file: 'lying.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!wahahou": {file: 'wahahou.wav', categories: [], categoriesFortnite: ["afterLose", "afterWin"]},
    "!chocola": {file: 'chocola.wav', categories: [], categoriesFortnite: []},
    "!profanity": {file: 'profanity.wav', categories: [], categoriesFortnite: []},
    "!tongue": {file: 'tongue.wav', categories: [], categoriesFortnite: ["beforeMatch"]},
    "!alright": {file: 'alright.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!goodbye": {file: 'goodbye.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!komtgoed": {file: 'komtgoed.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!poep": {file: 'poep.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!bingo": {file: 'bingo.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!myself": {file: 'myself.wav', categories: [], categoriesFortnite: ["afterLose", "afterWin"]},
    "!houston": {file: 'houston.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!try": {file: 'try.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!tears": {file: 'tears.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!endworld": {file: 'endworld.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!missyou": {file: 'missyou.wav', categories: [], categoriesFortnite: []},
    "!together": {file: 'together.wav', categories: [], categoriesFortnite: ["beforeMatch"]},
    "!steeds": {file: 'steeds.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!hello": {file: 'hello.wav', categories: [], categoriesFortnite: []},
    "!tochniet": {file: 'tochniet.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!skill": {file: 'skill.wav', categories: [], categoriesFortnite: ["afterWin"]},
    "!dumb": {file: 'dumb.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!biem": {file: 'biem.wav', categories: [], categoriesFortnite: ["afterWin"]},
    "!fine": {file: 'fine.mp3', categories: [], categoriesFortnite: ["afterLose"]},
    "!duuun": {file: 'duuun.mp3', categories: [], categoriesFortnite: ["afterWin"]},
    "!happened": {file: 'happened.mp3', categories: [], categoriesFortnite: ["afterLose", "afterWin"]},
    "!killmyself": {file: 'killmyself.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!rustaagh": {file: 'rustaagh.mp3', categories: [], categoriesFortnite: ["afterWin"]},
    "!dunked": {file: 'happened.wav', categories: [], categoriesFortnite: ["afterLose", "afterWin"]},
    "!infinity": {file: 'infinity.mp3', categories: [], categoriesFortnite: ["beforeMatch"]},
    "!sad": {file: 'sad.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!herewego": {file: 'herewego.mp3', categories: [], categoriesFortnite: ["beforeMatch"]},
    "!mission": {file: 'mission.mp3', categories: [], categoriesFortnite: ["beforeMatch"]},
    "!rip": {file: 'rip.mp3', categories: [], categoriesFortnite: ["afterLose"]},
    "!trombone": {file: 'trombone.mp3', categories: [], categoriesFortnite: ["afterLose"]},
    "!start": {file: 'start.mp3', categories: [], categoriesFortnite: ["beforeMatch"]},
    "!noone": {file: 'noone.mp3', categories: [], categoriesFortnite: ["afterWin", "afterLose"]},
    "!damnson": {file: 'damnson.mp3', categories: [], categoriesFortnite: ["afterLose", "afterWin"]},
    "!tadaah": {file: 'tadaah.mp3', categories: [], categoriesFortnite: ["afterLose", "afterWin"]},
    "!pressure": {file: 'pressure.wav', categories: [], categoriesFortnite: ["beforeMatch"]},
    "!kapitein": {file: 'kapitein.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!nigga": {file: 'nigga.mp3', categories: [], categoriesFortnite: ["afterLose"]},
    "!like": {file: 'like.mp3', categories: [], categoriesFortnite: ["afterLose","afterWin"]},
    "!smooth": {file: 'smooth.wav', categories: [], categoriesFortnite: ["afterLose","afterWin"]},
    "!behappy": {file: 'behappy.wav', categories: [], categoriesFortnite: ["afterLose","afterWin","beforeMatch"]},
    "!river": {file: 'river.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!mylife": {file: 'mylife.wav', categories: [], categoriesFortnite: ["beforeMatch"]},
    "!gratis": {file: 'gratis.wav', categories: [], categoriesFortnite: ["afterWin"]},
    "!how": {file: 'how.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!letsdoit": {file: 'letsdoit.wav', categories: [], categoriesFortnite: ["beforeMatch"]},
    "!uhm": {file: 'uhm.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!hehe": {file: 'hehe.wav', categories: [], categoriesFortnite: ["afterWin"]},
    "!rutte": {file: 'rutte.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!gohome": {file: 'gohome.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!whatyoudoing": {file: 'whatyoudoing.wav', categories: [], categoriesFortnite: ["afterLose","afterWin"]},
    "!dontthinkso": {file: 'dontthinkso.wav', categories: [], categoriesFortnite: ["afterLose","beforeMatch"]},
    "!ruined": {file: 'ruined.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!vibeit": {file: 'vibeit.wav', categories: [], categoriesFortnite: ["beforeMatch"]},
    "!omgwow": {file: 'omgwow.mp3', categories: [], categoriesFortnite: ["afterLose","afterWin"]},
    "!sperdnigga": {file: 'sperdnigga.mp3', categories: [], categoriesFortnite: ["afterLose"]},
    "!mbaku": {file: 'mbaku.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!meneerdeboer": {file: 'meneerdeboer.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!hellothere": {file: 'hellothere.wav', categories: [], categoriesFortnite: ["afterWin"]},
    "!running": {file: 'running.mp3', categories: [], categoriesFortnite: ["afterLose"]},
    "!cyka": {file: 'cyka.wav', categories: [], categoriesFortnite: ["afterLose","afterWin"]},
    "!verkeerd": {file: 'verkeerd.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!klaas": {file: 'klaas.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!sjoerd": {file: 'sjoerd.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!wout": {file: 'wout.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!bush": {file: 'bush.wav', categories: [], categoriesFortnite: []},
    "!familiar": {file: 'familiar.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!freedom": {file: 'freedom.wav', categories: [], categoriesFortnite: ["beforeMatch"]},
    "!perfect": {file: 'perfect.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!kind": {file: 'kind.wav', categories: [], categoriesFortnite: []},
    "!communicate": {file: 'communicate.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!mad": {file: 'mad.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!seatbelts": {file: 'seatbelts.wav', categories: [], categoriesFortnite: ["beforeMatch"]},
    "!roads": {file: 'roads.wav', categories: [], categoriesFortnite: ["beforeMatch"]},
    "!shirley": {file: 'shirley.wav', categories: [], categoriesFortnite: []},
    "!friendship": {file: 'friendship.wav', categories: [], categoriesFortnite: ["afterWin"]},
    "!prepare": {file: 'prepare.wav', categories: [], categoriesFortnite: []},
    "!goodbye2": {file: 'goodbye2.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!goodbye3": {file: 'goodbye3.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!goodbye4": {file: 'goodbye4.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!goodbye5": {file: 'goodbye5.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!anotherone": {file: 'anotherone.wav', categories: [], categoriesFortnite: ["afterLose", "afterWin"]},
    "!liefde": {file: 'liefde.wav', categories: [], categoriesFortnite: ["afterLose"]},
    "!mahboi": {file: 'mahboi.mp3', categories: [], categoriesFortnite: ["afterLose", "afterWin"]},
    "!leftchat": {file: 'leftchat.mp3', categories: [], categoriesFortnite: []},
    "!run": {file: 'run.mp3', categories: [], categoriesFortnite: []},
    "!hallo": {file: 'hallo.mp3', categories: [], categoriesFortnite: ["beforeMatch"]},
};

exports.responseObject = {
    "ayy": "Ayy, lmao!",
    "wat": "Say what?",
    "lol": "roflmaotntpmp",
    "!test": "Yes I am online :)",
    "ping": "pong",
    "pong": "ping",
    "pief": "paf",
    "paf": "pief",
    "sup": "The Sky",
    "oh shit waddup": "The Sky",
    "!stats steam holmes": "!stats steam 76561198152188680",
    "!niceshot": "https://gfycat.com/QuarrelsomeUnawareIslandwhistler",
    "nice shot": "https://gfycat.com/QuarrelsomeUnawareIslandwhistler",
    "🏓": "🏓",
    "help": "Need help? (Yes PP/No PP)",
    "!help": "Need help? (Yes PP/No PP)",
    "no pp": "Okay! xx 🏓",
    "yes pp": "Send `!commands` for a list of commands",
    "regret": "Did you say regret!?",
    "dab": "Did you say dab!?",
    "!hackerman": "https://giphy.com/gifs/fury-kung-hackerman-QbumCX9HFFDQA",
    "hihi": "met",
    "!fortnite": "`!afterLose`\n`!afterWin`\n`!beforeMatch`"
};

exports.imageObject = {
    "regret": './regret.png',
    "!regret": './regret.png',
    "dab": './dab.png',
    "nigga": './nigga.png',
    "really nigga": './nigga.png',
    "!nigga": './nigga.png',
    "meirl": './meirl2.png',
    "meirll": './meirl.png',
    "meirlll": './meirlmerge.jpg',
    "hihi met": './sisi2.jpg',
    "hihi": './sisi.png'
}

exports.emojiObject = {
    "gotem": "457243138617245717",
    "yeah": "458285126883999745",
    "perfectly balanced": "459295496255569970"
}

exports.embeds = {
    "!commands": Embeds.commands,
    "!all": Embeds.allCommands,
    "!chat": Embeds.chatCommands,
    "!voicechat": Embeds.voiceCommands
}